### ISSUE TITLE
Multiple problems trying to use this action: bad version, no JSON instruction and missing index.js

### ISSUE THREAD

**Issue by TestGTR** [zentered/issue-forms-body-parser#2]
**Describe the bug**

Multiple errors after multiples tries.

**To Reproduce**

### Unable to use the released version

Trying to use this version: https://github.com/zentered/issue-forms-body-parser/releases/tag/v1.1.0

```yaml
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@1.1
      - run: echo "${{ JSON.stringify(steps.parse.outputs.data) }}"
```

Error:

```log
Unable to resolve action `zentered/issue-forms-body-parser@1.1`, unable to find version `1.1`
```

### Unrecognized named-value: 'JSON'

Running the example given into README:

```yaml
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@1.0.0
      - run: echo "${{ JSON.stringify(steps.parse.outputs.data) }}"
```

Error:

```log
Invalid workflow file: .github/workflows/issue_comment.yml#L38
The workflow is not valid. .github/workflows/issue_comment.yml (Line: 38, Col: 14): Unrecognized named-value: 'JSON'. Located at position 1 within expression: JSON.stringify(steps.parse.outputs.data)
```

### Missing `dist/index.js`

```yaml
      - name: GitHub Issue Forms Body Parser
        id: parsezt
        uses: zentered/issue-forms-body-parser@main
        # same error with: @1.0.2
```

Error:

```log
2022-03-20T15:48:57.9592858Z ##[group]Run zentered/issue-forms-body-parser@main
2022-03-20T15:48:57.9593184Z ##[endgroup]
2022-03-20T15:48:57.9685273Z ##[error]File not found: '/home/runner/work/_actions/zentered/issue-forms-body-parser/main/dist/index.js'
```

**Expected behavior**

Works as described. Release published on Action marketplace to test against (but it seems
