### ISSUE TITLE
Feature request: Allow to specify the content to parse

### ISSUE THREAD

**Issue by benja-M-1** [zentered/issue-forms-body-parser#26]
### Is your feature request related to a problem? Please describe.

Hi there 👋 

I have a workflow that runs when an issue is created, reopened, edited. Now, I'd like to run this workflow again when someone comments `/run` with https://github.com/peter-evans/slash-command-dispatch. This will trigger the workflow with either a repository_dispatch or a workflow_dispatch. In any case, I could get the issue id from the payload/inputs. This will allow me to fetch the issue to then parse the content. 

### Describe the solution you would like

That would be awesome if I could provide a `body` parameter to the step:

```yaml
      - id: read_issue_body 
        run: echo "body=$(gh issue view ${{ inputs.issue_number }} --json body)" >> $GITHUB_OUTPUT

      - name: Parse issue body
        id: parse
        uses: zentered/issue-forms-body-parser@v1.5.1
        with:
            body: ${{ steps.read_issue_body.output.body }}
```

### Describe alternatives you have considered

I could use a `actions/github-script` and use some js in it to do that.

```yaml
      - id: read_issue_body 
        run: echo "body=$(gh issue view ${{ inputs.issue_number }} --json body)" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3

      - run: npm install @zentered/issue-forms-body-parser

      - name: Get extensions
        id: extract_extensions
        uses: actions/github-script@v6
        with:
          script: |
            const { default: parser } = await import('${{ github.workspace }}/node_modules/@zentered/issue-forms-body-parser/pkg/parse.js');
            try {
              const content = await parser(${{ steps.read_issue_body.output.body }});
              core.setOutput(content);
            }
            // ...
```
