### ISSUE TITLE
Provide option to return a hash / dictionary rather than an array

### ISSUE THREAD

**Issue by andyfeller** [zentered/issue-forms-body-parser#6]
### Is your feature request related to a problem? Please describe.

When working with the results from parsing the issue form, it takes additional effort to find the right array index containing the section I need.  Since each section is uniquely named, it would be easier to return a dictionary or hash with the results indexed by id instead.

So instead of:

```json
[
{
  "id": "repository-name",
  "title": ">>Repository name<<",
  "text": "test-zentered-issue-form-parser-2\n"
},
{
  "id": "repository-description",
  "title": ">>Repository description<<",
  "text": "*No response*\n"
},
{
  "id": "repository-visibility",
  "title": ">>Repository visibility<<",
  "text": "Internal\n"
},
{
  "id": "repository-access",
  "title": ">>Repository access<<",
  "text": "@tinyfists/monks, read\n"
},
{
  "id": "compliance-programs",
  "title": ">>Compliance programs<<",
  "list": [
    {
      "checked": false,
      "text": "GDPR"
    },
    {
      "checked": true,
      "text": "HIPAA"
    },
    {
      "checked": true,
      "text": "PCI"
    },
    {
      "checked": false,
      "text": "..."
    }
  ],
  "text": "*   [ ] GDPR\n*   [x] HIPAA\n*   [x] PCI\n*   [ ] ...\n"
}
]
```

something like this could be returned:

```json
{
	"repository-name": {
		"id": "repository-name",
		"title": ">>Repository name<<",
		"text": "test-zentered-issue-form-parser-2\n"
	},
	"repository-description": {
		"id": "repository-description",
		"title": ">>Repository description<<",
		"text": "*No response*\n"
	},
	"repository-visibility": {
		"id": "repository-visibility",
		"title": ">>Repository visibility<<",
		"text": "Internal\n"
	},
	"repository-access": {
		"id": "repository-access",
		"title": ">>Repository access<<",
		"text": "@tinyfists/monks, read\n"
	},
	"compliance-programs": {
		"id": "compliance-programs",
		"title": ">>Compliance programs<<",
		"list": [
			{
				"checked": false,
				"text": "GDPR"
			}, {
				"checked": true,
				"text": "HIPAA"
			}, {
				"checked": true,
				"text": "PCI"
			}, {
			"checked": false,
			"text": "..."
			}
		],
		"text": "*   [ ] GDPR\n*   [x] HIPAA\n*   [x] PCI\n*   [ ] ...\n"
	}
}
```

_I could give or take redundantly including the "id" within the payload along with being the key._

### Describe the solution you would like

Provide an option that allows the user to indicate whether an array of objects or a hash / dictionary should be returned.

### Additional context

Love the work!

**Comment by andyfeller** [comment]
I'm also realizing that the newlines are being included as of `v1.2.0`, too.

**Comment by PatrickHeneise** [comment]
Thanks Andy! I'll fix the newline issue straight away.

As for the hash, you're right, it would be a lot easier to access the items. One minor concern I have is if the order of the items is important, the array is the safer choice.

Probably a hash/object with an `order` number would be a good way around that, or two different exports one as array and one as object, what do you think?

I have a working example here btw.: https://github.com/gitevents/ics/blob/main/src/fetch-issues.js#L79

**Comment by steffen** [comment]
I agree that allowing direct access to the keys would be nice(r). 😊

> One minor concern I have is if the order of the items is important, the array is the safer choice.

It looks like since ES2015 the property order of objects with string keys is guaranteed and predictable:
https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/

An alternative could be https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map,
but I have been relaying on property order of standard objects before as well without issues so far.

Having said that, I believe the order is not too important once you have unique keys. Just my two cents. 😊

**Comment by andyfeller** [comment]
@PatrickHeneise @steffen : thank you both for following up so quickly!  I had not considered someone holding the order of the inputs important. 🤔 

**If we're unable to find an acceptable way to handle order with a map / dict, would it be acceptable trade off for those who use this option?**  Again, I'm not asking the action change for everyone, just those who want the results in that particular form factor.

**Comment by andyfeller** [comment]
Just to confirm, **¿is the expectation that the current array output format would expect someone to find unique sections like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#find_an_object_in_an_array_by_one_of_its_properties?**

```javascript
const inventory = [
  {name: 'apples', quantity: 2},
  {name: 'bananas', quantity: 0},
  {name: 'cherries', quantity: 5}
];

const result = inventory.find( ({ name }) => name === 'cherries' );

console.log(result) // { name: 'cherries', quantity: 5 }
```

**Comment by PatrickHeneise** [comment]
The basic thought behind this was that markdown tokens are stored in arrays to keep the content _as is_. But you're right, the point of this is to extract "structured" data, so it makes sense to return this as an object. I'll get to that later, thanks for the suggestion!

**Comment by andyfeller** [comment]
![thank you, patrick](https://c.tenor.com/tcBXbnJIowEAAAAC/thank-you-thanks-to-you.gif)

You're doing good and helpful work, Patrick; I appreciate you being so thoughtful and considering of the ask.

**Comment by PatrickHeneise** [comment]
Nothing to thank for. We're using the action/package ourselves at GitEvents and these changes make things easier downstream :)

Please have a look at the PR and let me know if the changes are what you expected, then I'll merge that. It _should_ result in a 2.0.0 if everything works.

**Comment by andyfeller** [comment]
@PatrickHeneise : will do!

For posterity, this is how leveraging `v1.2.0` release required working with the results:

```yaml
      - name: Create repository
        id: create-repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CREATE_REPO_TOKEN }}
          script: |
            const issueForm = ${{ steps.parse.outputs.data }}
            const name = issueForm.find( ({ id }) => id === 'repository-name' ).text.trim();
            const description = issueForm.find( ({ id }) => id === 'repository-description' ).text.trim();
            const visibility = issueForm.find( ({ id }) => id === 'repository-visibility' ).text.trim().toLowerCase();

            return await github.rest.repos.createInOrg({
              org: context.repo.owner,
              name: name,
              description: description,
              visibility: visibility,
              auto_init: true,
            })
```

_Just wanted to show a before and after, kind of like a home improvement show_ 🤓

**Comment by andyfeller** [comment]
After testing out the changes from #10 , this is what the resulting code looked like:

```yaml
      - name: Create repository
        id: create-repo
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CREATE_REPO_TOKEN }}
          script: |
            const issueForm = ${{ steps.parse.outputs.data }}
            const name = issueForm["repository-name"].text;
            const description = issueForm["repository-description"].text;
            const visibility = issueForm["repository-visibility"].text.toLowerCase();

            return await github.rest.repos.createInOrg({
              org: context.repo.owner,
              name: name,
              description: description,
              visibility: visibility,
              auto_init: true,
            })
```

Beyond these changes, do you think it is worth while having a separate follow up issue like the one I posted demonstrating how someone would use the results?
